import type { ColorEntry, ColorRoles, InterfaceCue } from '@/lib/guidelines';
import { CopyValue } from './copy-value';

function Palette({ id, title, entries }: { id: string; title: string; entries: ColorEntry[] }) {
  return <section className="guide-section" aria-labelledby={id}><h2 id={id}>{title}</h2><div className="color-list">{entries.map((entry) => <article className="color-row" key={entry.token} data-color-token={entry.token}><div className="color-summary"><span className="color-chip" style={{ background: entry.hex }} aria-hidden="true" /><span className="color-name"><strong>{entry.role}</strong><code>{entry.token}</code>{entry.aliases.length > 0 && <small>Also: {entry.aliases.join(', ')}</small>}</span><code className="color-hex">{entry.hex}</code><CopyValue value={entry.hex} label={`${entry.role} HEX`} /></div><details className="color-details"><summary>See more color values</summary><dl><div><dt>RGB</dt><dd><code>{entry.rgb}</code></dd></div><div><dt>HSL</dt><dd><code>{entry.hsl}</code></dd></div><div><dt>OKLCH</dt><dd><code>{entry.oklch}</code></dd></div><div><dt>Lab D50</dt><dd><code>{entry.lab.replace(' (D50)', '')}</code></dd></div></dl><p>{entry.print}</p></details></article>)}</div></section>;
}

function CueRows({ cues }: { cues: InterfaceCue[] }) {
  return <tbody>{cues.map((cue) => <tr key={cue.id}><th scope="row">{cue.label}</th><td><code>{cue.hex}</code></td><td>{cue.use}</td><td>{cue.foreground} foreground, {cue.foreground_contrast.toFixed(2)}:1; {cue.surface_contrast.toFixed(2)}:1 against {cue.surface}</td><td>{cue.non_color_cue}</td></tr>)}</tbody>;
}

export function ColorReference({ palettes, roles }: { palettes: { dark: ColorEntry[]; light: ColorEntry[] }; roles: ColorRoles | null }) {
  const shared = roles?.identity.flatMap((color) => roles.interface.dark.filter((cue) => ['action', 'warning'].includes(cue.id) && cue.hex === color.hex).map((cue) => ({ color, cue })))[0];
  const sample = shared?.color ?? roles?.identity[0];
  const exampleCue = shared?.cue ?? roles?.interface.dark.find((cue) => cue.id === 'warning');
  return <><p className="guide-lead">HEX is the canonical screen reference. Formal identity colors belong to approved brand applications; interface cues communicate actions and states with words, icons, outlines, or attributes as well as color.</p>
    {roles && <><section className="guide-section" aria-labelledby="formal-colors"><h2 id="formal-colors">Formal identity colors</h2><p>A color used in artwork is not automatically a warning or action cue.</p><div className="guide-table-scroll" role="region" aria-label="Formal identity color table" tabIndex={0}><table><thead><tr><th>Color</th><th>HEX</th><th>Source</th><th>Use</th></tr></thead><tbody>{roles.identity.map((row) => <tr key={row.id}><th scope="row">{row.label}</th><td><code>{row.hex}</code></td><td><code>{row.source}</code></td><td>{row.use}</td></tr>)}</tbody></table></div><h3>Approved combinations and artwork</h3><div className="guide-table-scroll" role="region" aria-label="Approved identity combinations" tabIndex={0}><table><thead><tr><th>Application</th><th>Formal colors</th><th>Artwork</th><th>Use</th></tr></thead><tbody>{roles.identity_combinations.map((row) => <tr key={row.id}><th scope="row">{row.label}</th><td>{row.colors.map((id) => roles.identity.find((color) => color.id === id)?.label ?? id).join(', ')}</td><td><code>{row.artwork}</code></td><td>{row.use}</td></tr>)}</tbody></table></div>{sample && exampleCue && <p>Correct: use {sample.label} ({sample.hex}) in its approved identity application; pair the {exampleCue.label.toLowerCase()} cue ({exampleCue.hex}) with {exampleCue.non_color_cue.toLowerCase()}. Misuse: a lone identity swatch as the only {exampleCue.label.toLowerCase()} signal.</p>}</section>
      {(['dark', 'light'] as const).map((theme) => <section className="guide-section" aria-labelledby={`${theme}-cues`} key={theme}><h2 id={`${theme}-cues`}>Interface cues on {theme} surfaces</h2><p>A shared HEX value does not merge identity and interface roles. State meaning also requires the listed non-color cue.</p><div className="guide-table-scroll" role="region" aria-label={`${theme} interface cue table`} tabIndex={0}><table><thead><tr><th>Cue</th><th>HEX</th><th>Meaning</th><th>Measured pairing</th><th>Non-color cue</th></tr></thead><CueRows cues={roles.interface[theme]} /></table></div></section>)}</>}
    <Palette id="dark-palette" title="Dark palette" entries={palettes.dark} /><Palette id="light-palette" title="Light palette" entries={palettes.light} /></>;
}
