// GENERATED by shruggie-brandbuilder/gen_enforcement.py for ShruggieTech.
// Regenerate rather than hand-edit.
//
// ESLint, not oxlint. oxlint 1.79 implements none of the no-restricted-* rules,
// so an oxlint-based adherence config fails to parse or silently does nothing.
// These selectors need a real ESTree engine.
//
//   npx eslint --config enforcement/eslint.brand.mjs .

export default [
  {
    files: ["**/*.{js,jsx,ts,tsx}"],
    languageOptions: {
      parserOptions: { ecmaVersion: "latest", sourceType: "module",
                       ecmaFeatures: { jsx: true } },
    },
    rules: {
      "no-restricted-syntax": ["error", ...[
  {
    "selector": "Literal[value=/#[0-9a-fA-F]{3,8}\\b/]",
    "message": "Raw hex colour. Use a design-system token: var(--primary), var(--muted-foreground), or a Tailwind class bound to one."
  },
  {
    "selector": "Literal[value=/\\b\\d+px\\b/]",
    "message": "Raw px value. Use a spacing or radius token. The scale is 4/8/12/16/24/32/48/64/96/120; radii are 6/8/12/16."
  },
  {
    "selector": "Literal[value=/\\b(?:rgb|rgba|hsl|hsla)\\(/]",
    "message": "Raw colour function. Use a design-system token."
  },
  {
    "selector": "Literal[value=/font-family\\s*:\\s*(?!['\\\"]?(?:Space Grotesk|Geist|Geist Mono))/i]",
    "message": "Font outside the system. Available: Space Grotesk, Geist, Geist Mono. Never a fourth family."
  },
  {
    "selector": "Literal[value=/font-weight\\s*:\\s*(?:100|200|300|600|800|900)/]",
    "message": "Weight not shipped. Geist has 400/500, Geist Mono has 400, Space Grotesk has 500/700. Anything else synthesises a faux bold."
  },
  {
    "selector": "Property[key.name='fontFamily'] > Literal[value=/^(?!['\\\"]?(?:Space Grotesk|Geist|Geist Mono))/i]",
    "message": "Font outside the system. Available: Space Grotesk, Geist, Geist Mono. Never a fourth family."
  },
  {
    "selector": "Property[key.name='fontWeight'] > Literal[value=100], Property[key.name='fontWeight'] > Literal[value=200], Property[key.name='fontWeight'] > Literal[value=300], Property[key.name='fontWeight'] > Literal[value=600], Property[key.name='fontWeight'] > Literal[value=800], Property[key.name='fontWeight'] > Literal[value=900], Property[key.name='fontWeight'] > Literal[value=/^(100|200|300|600|800|900)$/]",
    "message": "Weight not shipped. Geist has 400/500, Geist Mono has 400, Space Grotesk has 500/700. Anything else synthesises a faux bold."
  },
  {
    "selector": "JSXAttribute[name.name='className'] Literal[value=/\\b(?:bg|text|border)-(?:slate|gray|zinc|neutral|stone|red|green|blue|emerald|cyan|violet)-\\d{2,3}\\b/]",
    "message": "Stock Tailwind palette class. Use the semantic slots: bg-background, bg-card, text-foreground, text-muted-foreground, bg-primary, border-border."
  },
  {
    "selector": "JSXAttribute[name.name='className'] Literal[value=/\\brounded-(?:none|full|\\[)/]",
    "message": "Radius outside the pegs, unless this is a pill. Use rounded-sm (6), rounded-md (8), rounded-xl (12), rounded-2xl (16)."
  },
  {
    "selector": "JSXOpeningElement[name.name='Button'] > JSXAttribute > JSXIdentifier[name!=/^(?:aria-label|children|className|disabled|id|key|onChange|onClick|onSubmit|ref|size|style|variant)$/]",
    "message": "<Button> does not accept that prop. Declared: variant, size, children."
  },
  {
    "selector": "JSXOpeningElement[name.name='Button'] > JSXAttribute[name.name='variant'] > Literal[value!=/^(?:primary|secondary|ghost)$/]",
    "message": "<Button variant> must be one of 'primary' | 'secondary' | 'ghost'."
  },
  {
    "selector": "JSXOpeningElement[name.name='Button'] > JSXAttribute[name.name='size'] > Literal[value!=/^(?:sm|md|lg)$/]",
    "message": "<Button size> must be one of 'sm' | 'md' | 'lg'."
  },
  {
    "selector": "JSXOpeningElement[name.name='Badge'] > JSXAttribute > JSXIdentifier[name!=/^(?:aria-label|children|className|disabled|id|key|onChange|onClick|onSubmit|ref|style|tone)$/]",
    "message": "<Badge> does not accept that prop. Declared: tone, children."
  },
  {
    "selector": "JSXOpeningElement[name.name='Badge'] > JSXAttribute[name.name='tone'] > Literal[value!=/^(?:accent|emphasis|neutral|danger)$/]",
    "message": "<Badge tone> must be one of 'accent' | 'emphasis' | 'neutral' | 'danger'."
  },
  {
    "selector": "JSXOpeningElement[name.name='Card'] > JSXAttribute > JSXIdentifier[name!=/^(?:aria-label|children|className|disabled|id|key|onChange|onClick|onSubmit|ref|style)$/]",
    "message": "<Card> does not accept that prop. Declared: children."
  },
  {
    "selector": "JSXOpeningElement[name.name='Divider'] > JSXAttribute > JSXIdentifier[name!=/^(?:aria-label|children|className|disabled|id|key|onChange|onClick|onSubmit|ref|style)$/]",
    "message": "<Divider> does not accept that prop. Declared: none."
  },
  {
    "selector": "JSXOpeningElement[name.name='SectionHeading'] > JSXAttribute > JSXIdentifier[name!=/^(?:aria-label|children|className|description|disabled|eyebrow|id|key|onChange|onClick|onSubmit|ref|style|title)$/]",
    "message": "<SectionHeading> does not accept that prop. Declared: eyebrow, title, description."
  },
  {
    "selector": "JSXOpeningElement[name.name='Input'] > JSXAttribute > JSXIdentifier[name!=/^(?:aria-label|children|className|disabled|error|id|key|label|onChange|onClick|onSubmit|placeholder|ref|required|style|type)$/]",
    "message": "<Input> does not accept that prop. Declared: label, type, placeholder, required, error."
  },
  {
    "selector": "JSXOpeningElement[name.name='Textarea'] > JSXAttribute > JSXIdentifier[name!=/^(?:aria-label|children|className|disabled|error|id|key|label|onChange|onClick|onSubmit|placeholder|ref|required|rows|style)$/]",
    "message": "<Textarea> does not accept that prop. Declared: label, rows, placeholder, required, error."
  },
  {
    "selector": "JSXOpeningElement[name.name='Select'] > JSXAttribute > JSXIdentifier[name!=/^(?:aria-label|children|className|disabled|error|id|key|label|onChange|onClick|onSubmit|options|ref|required|style)$/]",
    "message": "<Select> does not accept that prop. Declared: label, options, required, error."
  }
]],
      "no-restricted-imports": ["error", { patterns: [{
        group: ["*/components/core/*", "*/components/forms/*"],
        message: "Import design-system components from the package index, not internals.",
      }]}],
    },
  },
  { ignores: ["tokens/**", "**/node_modules/**", "**/.next/**", "**/dist/**"] },
]
