#!/usr/bin/env python3
"""Generate deterministic cross-host conformance fixtures for one brand kit."""

import hashlib
import json
import re
import sys
import textwrap
from pathlib import Path

from conformance_contract import evaluate_trace, load_policy, sha256_file


HERE = Path(__file__).resolve().parent
DECISIONS = HERE.parent / "references" / "conformance-baseline-decisions.json"
SAFE_CRATE = re.compile(r"[^a-z0-9_]+")
SOURCE_REVISION = re.compile(r"^[0-9a-f]{40,64}$")


def _write_text(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def _write_json(path, payload):
    _write_text(path, json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False) + "\n")


def _read_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _rust_fixture(crate_name):
    cargo = """[package]
name = "{crate_name}"
version = "1.0.0"
edition = "2024"
rust-version = "1.95"
publish = false

[lib]
path = "src/lib.rs"
""".format(crate_name=crate_name)
    lock = """# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "{crate_name}"
version = "1.0.0"
""".format(crate_name=crate_name)
    library = r'''#[derive(Clone, Copy, Debug)]
pub struct Rect { pub x: f32, pub y: f32, pub width: f32, pub height: f32 }

#[derive(Clone, Copy, Debug)]
pub struct Insets { pub top: f32, pub right: f32, pub bottom: f32, pub left: f32 }

#[derive(Clone, Copy, Debug)]
pub struct Envelope {
    pub viewport_width: f32,
    pub viewport_height: f32,
    pub safe: Insets,
    pub ime_block_end: f32,
    pub safe_area_owners: u8,
    pub ime_owners: u8,
    pub required_control: Rect,
}

pub fn diagnostics(envelope: Envelope) -> Vec<&'static str> {
    let mut result = Vec::new();
    if envelope.safe_area_owners != 1 || envelope.ime_owners != 1 {
        result.push("host.duplicate-owner");
    }
    let safe_count = envelope.safe_area_owners.max(1) as f32;
    let ime_count = envelope.ime_owners.max(1) as f32;
    let left = envelope.safe.left * safe_count;
    let right = envelope.viewport_width - envelope.safe.right * safe_count;
    let top = envelope.safe.top * safe_count;
    let bottom = envelope.viewport_height - envelope.safe.bottom * safe_count - envelope.ime_block_end * ime_count;
    let control = envelope.required_control;
    let contained = control.x >= left && control.y >= top && control.x + control.width <= right && control.y + control.height <= bottom;
    if !contained { result.push("host.control-obstructed"); }
    result
}
'''
    tests = r'''use tauri_android_conformance::{diagnostics, Envelope, Insets, Rect};

#[test]
fn known_bad_double_consumption_fails() {
    let failures = diagnostics(Envelope {
        viewport_width: 412.0, viewport_height: 915.0,
        safe: Insets { top: 38.0, right: 0.0, bottom: 24.0, left: 0.0 },
        ime_block_end: 0.0, safe_area_owners: 2, ime_owners: 1,
        required_control: Rect { x: 16.0, y: 850.0, width: 56.0, height: 56.0 },
    });
    assert!(failures.contains(&"host.duplicate-owner"));
    assert!(failures.contains(&"host.control-obstructed"));
}

#[test]
fn corrected_orientation_and_ime_states_pass() {
    let states = [
        Envelope { viewport_width: 412.0, viewport_height: 915.0, safe: Insets { top: 38.0, right: 0.0, bottom: 24.0, left: 0.0 }, ime_block_end: 0.0, safe_area_owners: 1, ime_owners: 1, required_control: Rect { x: 16.0, y: 812.0, width: 56.0, height: 56.0 } },
        Envelope { viewport_width: 915.0, viewport_height: 412.0, safe: Insets { top: 0.0, right: 24.0, bottom: 20.0, left: 38.0 }, ime_block_end: 160.0, safe_area_owners: 1, ime_owners: 1, required_control: Rect { x: 54.0, y: 148.0, width: 300.0, height: 44.0 } },
        Envelope { viewport_width: 430.0, viewport_height: 780.0, safe: Insets { top: 34.0, right: 0.0, bottom: 22.0, left: 0.0 }, ime_block_end: 0.0, safe_area_owners: 1, ime_owners: 1, required_control: Rect { x: 16.0, y: 690.0, width: 56.0, height: 56.0 } },
    ];
    for state in states { assert!(diagnostics(state).is_empty()); }
}
'''
    return cargo, lock, library, tests.replace("tauri_android_conformance", crate_name)


def _go_fixture(module_name):
    go_mod = "module %s\n\ngo 1.22\n" % module_name
    source = r'''package conformance

type Rect struct { X, Y, Width, Height float64 }

func overlaps(left, right Rect) bool {
	return !(left.X+left.Width <= right.X || right.X+right.Width <= left.X || left.Y+left.Height <= right.Y || right.Y+right.Height <= left.Y)
}

func Validate(viewport Rect, reserved []Rect, controls []Rect) []string {
	problems := []string{}
	for _, control := range controls {
		if control.X < viewport.X || control.Y < viewport.Y || control.X+control.Width > viewport.X+viewport.Width || control.Y+control.Height > viewport.Y+viewport.Height {
			problems = append(problems, "host.control-obstructed")
		}
		for _, region := range reserved {
			if overlaps(control, region) { problems = append(problems, "host.titlebar-overlap") }
		}
	}
	return problems
}
'''
    tests = r'''package conformance

import "testing"

func TestWindowChromeProfiles(t *testing.T) {
	cases := []struct { viewport Rect; reserved []Rect; controls []Rect }{
		{Rect{0, 0, 1280, 900}, []Rect{{1136, 0, 144, 48}}, []Rect{{16, 8, 600, 44}}},
		{Rect{0, 0, 768, 720}, []Rect{{624, 0, 144, 48}}, []Rect{{16, 8, 500, 44}}},
	}
	for _, test := range cases {
		if failures := Validate(test.viewport, test.reserved, test.controls); len(failures) != 0 { t.Fatalf("unexpected failures: %v", failures) }
	}
}

func TestWindowChromeOverlapFails(t *testing.T) {
	failures := Validate(Rect{0, 0, 768, 720}, []Rect{{624, 0, 144, 48}}, []Rect{{650, 8, 100, 44}})
	if len(failures) != 1 || failures[0] != "host.titlebar-overlap" { t.Fatalf("expected titlebar diagnostic, got %v", failures) }
}
'''
    return go_mod, source, tests


def _browser_specimen(source, brand, manifest):
    profiles = "".join(
        '<button type="button" data-profile="%s">%s</button>' % (profile["id"], profile["id"].replace("-", " "))
        for profile in manifest["profiles"]
    )
    panel = (
        '<aside id="bb-conformance" aria-label="Conformance profiles" '
        'data-brand="%s" data-contract-version="%s">'
        '<p><strong>Browser reference</strong> <span id="bb-active-profile">normal desktop</span></p>'
        '<div role="group" aria-label="Capability profile">%s</div></aside>'
    ) % (brand["slug"], manifest["conformance_contract_version"], profiles)
    style = '<style>#bb-conformance{position:sticky;inset-block-start:0;z-index:50;padding:.75rem;background:Canvas;color:CanvasText;border-block-end:2px solid currentColor}#bb-conformance [role=group]{display:flex;gap:.5rem;flex-wrap:wrap}#bb-conformance button{min-block-size:44px;padding:.5rem .75rem;font:inherit}</style>'
    script = r'''<script>(()=>{const root=document.documentElement;const label=document.getElementById('bb-active-profile');const buttons=[...document.querySelectorAll('[data-profile]')];const select=(profile)=>{const selected=buttons.some(button=>button.dataset.profile===profile)?profile:'normal-desktop';root.dataset.conformanceProfile=selected;label.textContent=selected.replaceAll('-',' ');buttons.forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.profile===selected)));document.dispatchEvent(new CustomEvent('brandbuilder:profile',{detail:{profile:selected}}));};buttons.forEach(button=>button.addEventListener('click',()=>select(button.dataset.profile)));select(new URLSearchParams(location.search).get('profile')||'normal-desktop');})();</script>'''
    output = source.replace("</head>", style + "</head>", 1)
    output = output.replace("<body>", "<body>" + panel, 1)
    output = output.replace("</body>", script + "</body>", 1)
    return output


def generate_conformance(brand_json, kit_dir):
    brand_path = Path(brand_json)
    kit = Path(kit_dir)
    brand = _read_json(brand_path)
    consumer = _read_json(kit / "enforcement" / "consumer-contract.json")
    web = _read_json(kit / "web" / "adapter.json")
    egui = _read_json(kit / "native" / "egui" / "adapter.json")
    policy = load_policy()
    recipes = list(web.get("recipes") or [])
    if recipes != list(egui.get("recipes") or []):
        raise ValueError("web and egui recipe inventories disagree")
    versions = dict(consumer.get("versions") or {})
    versions["conformance_contract_version"] = policy["contract_version"]
    source_revision = (consumer.get("bundle") or {}).get("source_revision")
    if not SOURCE_REVISION.fullmatch(str(source_revision or "")):
        raise ValueError("consumer bundle source revision is unavailable for conformance")
    manifest = {
        "schema_version": 1,
        "conformance_contract_version": policy["contract_version"],
        "brand": brand["slug"],
        "brand_title": brand.get("title", brand["slug"]),
        "brand_version": brand.get("version"),
        "source_revision": source_revision,
        "versions": versions,
        "recipes": recipes,
        "diagnostic_classes": policy["diagnostic_classes"],
        "profiles": policy["profiles"],
        "host_tracks": policy["host_tracks"],
        "evidence_boundaries": {
            "browser_emulation_is_host_proof": False,
            "actual_host_status": "pending-proof",
        },
        "entries": {
            "browser": "conformance/browser/specimen.html",
            "traces": "conformance/evidence/traces.json",
            "tauri": "conformance/hosts/tauri-android/Cargo.toml",
            "wails": "conformance/hosts/wails-windows/go.mod",
            "egui": "native/egui/Cargo.toml",
            "baseline_decisions": "conformance/baseline-decisions.json",
        },
    }
    conformance = kit / "conformance"
    source_specimen = (kit / "web" / "specimen.html").read_text(encoding="utf-8")
    _write_text(conformance / "browser" / "specimen.html", _browser_specimen(source_specimen, brand, manifest))
    _write_json(conformance / "evidence" / "traces.json", policy["traces"])
    _write_json(conformance / "baseline-decisions.json", _read_json(DECISIONS))
    crate_name = SAFE_CRATE.sub("_", "%s_tauri_android_conformance" % brand["slug"]).strip("_")
    cargo, lock, library, rust_tests = _rust_fixture(crate_name)
    tauri = conformance / "hosts" / "tauri-android"
    _write_text(tauri / "Cargo.toml", cargo)
    _write_text(tauri / "Cargo.lock", lock)
    _write_text(tauri / "src" / "lib.rs", library)
    _write_text(tauri / "tests" / "ownership.rs", rust_tests)
    go_mod, go_source, go_tests = _go_fixture("brandbuilder/%s/wails_conformance" % brand["slug"])
    wails = conformance / "hosts" / "wails-windows"
    _write_text(wails / "go.mod", go_mod)
    _write_text(wails / "ownership.go", go_source)
    _write_text(wails / "ownership_test.go", go_tests)
    readme = textwrap.dedent("""\
        # {title} cross-host conformance

        GENERATED by BrandBuilder from the versioned conformance contract.

        - `browser/specimen.html` is browser-reference evidence only.
        - `hosts/tauri-android/` proves the Android WebView ownership boundary with Rust tests.
        - `hosts/wails-windows/` proves the Windows window-chrome boundary with Go tests.
        - `../native/egui/` remains the native rendered-state fixture.
        - `baseline-decisions.json` contains human decisions only. Candidate screenshots remain ignored artifacts.

        These fixtures do not claim actual host certification or downstream product outcomes.
        """).format(title=brand.get("title", brand["slug"]))
    _write_text(conformance / "README.md", readme)
    artifact_paths = [
        "conformance/browser/specimen.html", "conformance/evidence/traces.json",
        "conformance/baseline-decisions.json", "conformance/hosts/tauri-android/Cargo.toml",
        "conformance/hosts/tauri-android/Cargo.lock", "conformance/hosts/tauri-android/src/lib.rs",
        "conformance/hosts/tauri-android/tests/ownership.rs", "conformance/hosts/wails-windows/go.mod",
        "conformance/hosts/wails-windows/ownership.go", "conformance/hosts/wails-windows/ownership_test.go",
        "conformance/README.md",
    ]
    manifest["artifacts"] = [
        {"path": relative, "sha256": sha256_file(kit / relative)} for relative in artifact_paths
    ]
    _write_json(conformance / "manifest.json", manifest)
    return manifest


def verify_conformance(kit_dir):
    kit = Path(kit_dir)
    problems = []
    try:
        policy = load_policy()
        manifest = _read_json(kit / "conformance" / "manifest.json")
        brand = _read_json(kit / "brand.json")
        web = _read_json(kit / "web" / "adapter.json")
        egui = _read_json(kit / "native" / "egui" / "adapter.json")
        if manifest.get("conformance_contract_version") != policy["contract_version"]:
            problems.append("conformance contract version disagrees")
        if manifest.get("brand") != brand.get("slug") or manifest.get("brand_version") != brand.get("version"):
            problems.append("conformance brand identity disagrees")
        if manifest.get("recipes") != web.get("recipes") or manifest.get("recipes") != egui.get("recipes"):
            problems.append("conformance recipe inventory disagrees with adapters")
        if {item.get("id") for item in manifest.get("profiles") or []} != REQUIRED_PROFILE_IDS:
            problems.append("conformance profile matrix is incomplete")
        if {item.get("id") for item in manifest.get("host_tracks") or []} != REQUIRED_TRACK_IDS:
            problems.append("conformance host matrix is incomplete")
        if manifest.get("diagnostic_classes") != policy["diagnostic_classes"]:
            problems.append("conformance diagnostic classes disagree")
        if not SOURCE_REVISION.fullmatch(str(manifest.get("source_revision", ""))):
            problems.append("conformance source revision is missing or inexact")
        for track in manifest.get("host_tracks") or []:
            if track.get("status") != "supported":
                problems.append("%s reference status is not supported" % track.get("id", "unknown"))
            if track.get("renderer") == "web-react" and track.get("renderer_version") != "web-react-adapter-%s" % web.get("adapter_version"):
                problems.append("%s renderer version disagrees with the Web adapter" % track.get("id", "unknown"))
            if track.get("renderer") == "egui":
                expected_egui = str(((egui.get("crate") or {}).get("dependencies") or {}).get("egui", "")).lstrip("=")
                if track.get("renderer_version") != "egui-%s" % expected_egui:
                    problems.append("egui renderer version disagrees with the native adapter")
        if manifest.get("evidence_boundaries", {}).get("browser_emulation_is_host_proof") is not False:
            problems.append("browser evidence is allowed to substitute for host proof")
        seen = set()
        for artifact in manifest.get("artifacts") or []:
            relative = artifact.get("path")
            if not isinstance(relative, str) or relative in seen or ".." in relative or relative.startswith(("/", "\\")):
                problems.append("conformance artifact path is missing, duplicate, or unsafe")
                continue
            seen.add(relative)
            path = kit / relative
            if not path.is_file():
                problems.append("conformance artifact is missing: %s" % relative)
            elif artifact.get("sha256") != sha256_file(path):
                problems.append("conformance artifact checksum differs: %s" % relative)
        for trace_id, trace in policy["traces"].items():
            diagnostics = evaluate_trace(trace)
            if trace.get("expected") == "supported" and diagnostics:
                problems.append("%s unexpectedly fails: %s" % (trace_id, ", ".join(item["code"] for item in diagnostics)))
            if trace.get("expected") == "failed" and not diagnostics:
                problems.append("%s no longer demonstrates its known-bad failure" % trace_id)
        decisions = _read_json(kit / "conformance" / "baseline-decisions.json")
        if decisions.get("conformance_contract_version") != policy["contract_version"] or not isinstance(decisions.get("decisions"), list):
            problems.append("baseline decision ledger is invalid")
    except (OSError, ValueError, KeyError) as error:
        problems.append("conformance verification failed: %s" % error)
    return problems


REQUIRED_PROFILE_IDS = {
    "phone-portrait-touch", "phone-landscape-touch", "narrow-desktop", "normal-desktop",
    "reduced-motion", "forced-colors", "text-scale-200",
}
REQUIRED_TRACK_IDS = {"browser-react", "tauri-android", "wails-windows", "egui-native"}


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_conformance.py <brand.json> <kit-dir>")
    manifest = generate_conformance(sys.argv[1], sys.argv[2])
    print("generated cross-host conformance for %s (%d profiles, %d hosts)" % (
        manifest["brand"], len(manifest["profiles"]), len(manifest["host_tracks"])
    ))


if __name__ == "__main__":
    main()
