import { notFound } from 'next/navigation';
import { brands, brandBySlug } from '@/lib/brands';
import { pageMetadata } from '@/lib/metadata';
import { routeByPath } from '@/lib/routes';
import { StructuredData } from '@/components/structured-data';

export function generateStaticParams() { return brands.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const brand = brandBySlug((await params).slug); if (!brand) notFound(); return pageMetadata(routeByPath(`/${brand.slug}/downloads/`)); }
export default async function Downloads({ params }: { params: Promise<{ slug: string }> }) { const brand = brandBySlug((await params).slug); if (!brand) notFound(); const root = `/${brand.slug}/downloads/files`; const route = routeByPath(`/${brand.slug}/downloads/`); return <div className="shell"><StructuredData route={route} /><p className="eyebrow">Brand assets</p><h1>{brand.title} downloads</h1><p className="lede">Clearly organized source files for design, product, and implementation work.</p><ul className="download-list"><li><a href={`${root}/${brand.slug}-brand-guide.pdf`}><strong>Brand guide</strong><span>PDF standards and usage guidance</span></a></li><li><a href={`${root}/logos/svg/${brand.slug}-mark-color.svg`}><strong>Logo mark</strong><span>Primary SVG master</span></a></li><li><a href={`${root}/logos/svg/${brand.slug}-horizontal-color.svg`}><strong>Horizontal lockup</strong><span>Primary SVG master</span></a></li><li><a href={`${root}/icons/manifest.json`}><strong>Application icon suites</strong><span>Web, Android, Apple, macOS, and Windows asset index</span></a></li><li><a href={`${root}/icons/web/favicon.ico`}><strong>Web favicon bundle</strong><span>Classic multi-size browser ICO</span></a></li><li><a href={`${root}/icons/windows/classic/app.ico`}><strong>Windows application icon</strong><span>Classic multi-size desktop ICO</span></a></li><li><a href={brand.specimen}><strong>Type specimen</strong><span>Outlined SVG reference</span></a></li><li><a href={`/${brand.slug}/brand/r/theme.json`}><strong>shadcn theme</strong><span>Installable registry JSON</span></a></li></ul></div>; }
